### ISSUE TITLE
There's no licence file in the repo

### ISSUE THREAD

**Issue by tomnomnom** [tomnomnom/rawhttp#7]
There's no LICENCE file in the repo. Need to pick a licence and add it to the repo.

**Comment by fabaff** [comment]
This is a blocker.

rawhttp is a dependency for another Fedora package. Thus, I have to add it to the Fedora Package Collection as well  and Fedora require a license.

**Comment by tomnomnom** [comment]
@fabaff fixed; thank you for the reminder!

**Comment by fabaff** [comment]
Thanks for the super quick reaction.

Fedora package review: https://bugzilla.redhat.com/show_bug.cgi?id=1840622
